#noEnv ; #warn ; MWolff 2022 Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN; ->http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
#persistent
#SingleInstance force
sendMode Input
setWorkingDir %a_scriptDir%
menu, tray, add, Open Script Folder, Open_ScriptDir,
menu, tray, standard
menu, tray,tip, % "Whatj00l00king@?"
gb64 := "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABGdBTUEAALGPC/xhBQAAAYVpQ0NQSUNDIHByb2ZpbGUAACiRfZE9SMNQFIVPU0WRlg52EHXIUF20ICriKFUsgoXSVmjVweSlf9CkIUlxcRRcCw7+LFYdXJx1dXAVBMEfEEcnJ0UXKfG+pNAixguP93HePYf37gOERoWpZtcEoGqWkYrHxGxuVex5hQ9BhDCGIYmZeiK9mIFnfd1TN9VdlGd59/1ZQSVvMsAnEs8x3bCIN4hnNi2d8z5xmJUkhficeNygCxI/cl12+Y1z0WGBZ4aNTGqeOEwsFjtY7mBWMlTiaeKIomqUL2RdVjhvcVYrNda6J39hIK+tpLlOaxhxLCGBJETIqKGMCixEaddIMZGi85iHf9DxJ8klk6sMRo4FVKFCcvzgf/B7tmZhatJNCsSA7hfb/hgBenaBZt22v49tu3kC+J+BK63trzaA2U/S620tcgSEtoGL67Ym7wGXO8DAky4ZkiP5aQmFAvB+Rt+UA/pvgb41d26tc5w+ABma1fINcHAIjBYpe93j3b2dc/u3pzW/H4Z9cq/t2C+ZAAAJI0lEQVRIDQEYCef2AQQAFQAAAAAAAAAAAAAAAABj6+oDFRH/ALV8hWLPDDBxGR8kKSgQFwAWAQsADPoAAALx9wD36e8A6t7iAN3N1wAXBx5kysZfnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEABUAAAAAAAAAAABj6+oDFRH/BKi98mf2FgmPKy4GAiTx+QAE6vEABOr0AAIA/wD+//8AAgD/AAIGDAD+2Q8A9NHnAN/V19ff3Xkq393pAAAAAAAAAAAAAAAAAAAAAAABBAAVAAAAAABj6+oFCwgACtG/6MUkORgr/hQAABLb8gD6+PgA+fP4APr//wD8+f0A/fv8AP76/QAF//wADgH+AP0CAQANySYA3tXLAOfc5o/H0m1yAAAAAAAAAAAAAAAAAwIACwB4/OkDAQEADdms3ttJSB4g+vr3AAbf9AD4/PkA8+/3APr5/gD+9/wAEQoFAP//AAD47/kA9/b9APD0/QD08voAABHnABf6NwAODAA5CfszIePsuLAAAAAAAAAAAAMCAAsAPH51BNeW1sJJRScj6fX3APbn8QDw9fQA+PL5AP33/QD+9vwABiQRABoyGgD3HQ8A+vX6APng8wD99/0A+/f9AO/0/QD9GeUADe0tAA0N/TAJ9zMG5PC5vgAAAAACY+vqA8Vixm0oJCUy9fQAAO/a6gDt8/IA+vL5APzz+gD88/sAAvf9AAUpFQDtAAAACgQCACkaHgAD9v0A/PP9APzz/QD98v0A5d74AOcmyQAPFCUAERoOehkbEAAAAAAABAAAAAQHAfyDBPr7AOHq5wDs/vMAAPQAAAD5/wD/+v8AAPsAAPv5/wDxo9UAGBIJAP/3/QDc5vgA+vD8AP36/gD+/f0A/v3+AP/8/wDo3fcABBPJACQoLgDz636z5wByTQTWVbVlMz0xCu344ADq+fgAAAICAAD7AAAA+f8AAPoAAP/6AAD/+f4ACPv/AOH7BAD/9wAAC+30APnv/gD++/0A/fz+AP39/QD+/v0A/f7+AOv6/AAP+gwACxUOTBLuCwADBgA2yS8xOgDjDuMA+f3/AP/6/gD+9/8A/vf+AP71/gD+9v4AAff+AO8kFQAKSCMABSoUAPfc+QD11ugA9/D4APjx+AD59PkA+vP6APz3/AD28/0ACBnmABQDHgAL/zcZBB0VGAD58AIA+/z9AP7+AQD++QAAAPkBAAD4AAAA+v8A//cAAAb7/gAPIxYALBH/AOIDAQD3SCQA86nJAPf0AAAA/f8AAAAAAAABAAAAAQAAAQUAAPEN/gAYExIABgXiOwQNCAwA8AHxAPr8/QD9+QEAAPcAAAD4AAAA9wAA/vf+APny+QAB9vcAFQgEAPkAAAAC/v8A7wEBAAH0/wAI+AEAAAABAAEAAAABAP8A/gAAAP35AAD56foA/hcJAPr9+yIEBf0CAAEB/AD79/wA/vcBAAD3AAAA+AAA/fP9APbu9gD27vcACf3+AATzBQDw+gAA/wf/APUDAAATAAEA/AABAAEAAAAAAAAAAQAAAP4AAAD9AAAABfoAAAEIBgAFAwb5BPv2+wD9DPcA/ff9AP33AQAA+AAA/fL8APXr9gD57/oA/vX/AP0AAAD48wAAEPQAABoAAAD9AQAACgACAP0AAQACAAAAAAAAAP4A/wD/AAAA/QD/AAsBAAD+AfoA/wP/BATz7vIAEQD/AAL7/QD69wAA/fT+APft9wD68vsA//YAAAD2AQAFAwAAFPQAAAP5AAAECgAACQAAAAkBAwD8AQEAAAAAAAAAAAAAAP8A/gD/AP7//wAPCwEACRINAPX/+O4E9vPzAAnyBAADCf4A+/b+APnw+QD68/sA//YAAAD4AAAF+wEACAMAAAj+AAAOAQAA+v4AABEAAAADAQQA/gEBAAAAAAABAAAAAAD/AAIA/wD+AP4ABA4AAAALAPTx8vH0AhMSEYT/0vAA7+r+APr1+wD79fwAAPoBAAD6AQAB+QEABwABAAcBAgADAAAACAMAAAYCAQASAgAABAIDAAQCBAAFAgQABQIEAAIBBAAEAQQABQMEAPc3VQDw7OYMGAIQtwLT+H595+TgACnVKQD/8/wAAPsAAAD7AAAA+QEABwABAAgBAgAJAwMABgIAAA4K/wAWCf8AFAUAAAMCBAADAQQAAwEEAAIBAwAFAgMAAwEDAPVEAwAcKQAA6PXs9QUDB7sC5+XwAOzt77wMCvQADOkcAAIDAQAA+wEAAPsBAAUAAgAFAAEABgIDAAUCAAATAwAAGAIBAAwAAAAEAQMABAEDAAMBAwAEAQMAAwEEAO4/AgARQU4A9fz3APoMCIK2z2S6AgAAAADiCIhF2NjRADAMFgAH7RwAAPwBAAUAAQADAAEABQECAAYDAgAMAwAACgEAAAUAAAAE9QAAAgADAAMBAgAEAQIAAwEDAPA7AQD7SUoAGisAANns58bL0Z6wAAAAAAMCAAsA9PP5ABP/QfQEBfhGKBQjAO/cGAACDekAB/8CAAkAAgAD/wIA7fgXAPL4CADg5AAA36rdAATc8AADAAIAAwEBAPA8/wDZYkUANjYAANfU9f3MpodG9rKm2gAAAAABBAAVAAAAAAAAAAAAMQyHhR0hF3ofJi4A2eDuAPsA4QAG9wEABv8DAAQCAwAEAwEAAwECAPoVBAAJ6AAABAMAAOxC+QDueUgAFRUAAOHUAPj21ew621gqzwAAAAAAAAAAAQQAFQAAAAAAAAAAAAAAAAAxC4drDRYHlDI8OQDk6+sA/wMMAPnu+AASA+4ABwgBAAIBAgADBAEA5SkoABVEDAAaSQ4A5QAAAK7R+OMAAAA67zAe5AAAAAAAAAAAAAAAAAEEABUAAAAAAAAAAAAAAAAAAAAAAA8QCAAtEISmDh0QWSMsLAALFhUAAQ4MAAIOAQABDgAAAhQAAAYXAAD3CwAA0OP8AN7383zoFwme7zAe5wAAAAAAAAAAAAAAAAAAAAABBAAVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsLBgArI5Fv8fXmfAofFhQOGhEAAA0HAPIA+gDm9fLsD+fy7+uLWUcAAAD17zAe6gAAAAAAAAAAAAAAAAAAAAAAAAAA80/7jU1Zzw4AAAAASUVORK5CYII="

hbitmap := Png2hBitmap(gb64)			 	; Iconz := [] ; Iconz.Push(LoadPicture(hBitmap))
Menu, Tray, Icon, % "HBITMAP:*" hbitmap

Png2hBitmap(base64input, NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 3864 << !!A_IsUnicode)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &base64input, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &base64input, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}
return,

Open_ScriptDir:
toolTip %a_scriptFullPath%
z=explorer.exe /select,%a_scriptFullPath%
run %comspec% /C %z%,, hide
sleep 1250

ToolOff:
toolTip,
return
